volumes:
  timescaledb:

services:
  frontend:
    build:
      target: frontend
    ports:
      - 80:3000
    environment:
      API_PATH: http://solarmax-service:8000
      DB_PATH: /data/data.db
      ORIGIN: http://localhost

      DB_USE_DRIZZLE: true

      DATABASE_URL: "postgres://root:password@timescaledb:5432/solar-panel"
    volumes:
      - ./data:/data:rw
    depends_on:
      - timescaledb
    profiles:
      - services
  solarmax-service:
    build:
      target: solarmax-service
    profiles:
      - services
  update-scheduler:
    build:
      target: update-scheduler
    depends_on:
      - frontend
    environment:
      API_PATH: http://frontend:3000
      CRON_PATTERN: '0 * * * * *'
    profiles:
      - services
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solar-panel
    volumes:
      - timescaledb:/home/postgres/pgdata/data
    
